### PR TITLE
dhcp_lease_file requires an argument

### PR DESCRIPTION
**Pull request by bryanwb**

### CODE REVIEW

**Comment by portertech** [comment]
Seems like it would be cleaner to just have the method use config()?

**Comment by bryanwb** [comment]
works for me :) good catch

**Comment by portertech** [comment]
@bryanwb oh no, I was suggesting using the method, as it provides proper error handling on every sleep iteration, but use config() instead of an argument.

**Comment by bryanwb** [comment]
can u change accordingly? bedtime for me

**Comment by portertech** [comment]
Done :)

**Pull request closed without merging**
