### PR TITLE
allow mostly parallel operation

### PR DESCRIPTION
**Pull request by bryanwb**

### CODE REVIEW

**Comment by portertech** [comment]
@bryanwb Ah, this is new. I have had success in the past with parallel "test", I'm surprised I didn't hit this bump.

**Comment by portertech** [comment]
https://github.com/opscode/test-kitchen/blob/1.0/lib/kitchen/driver/base.rb#L194

**Comment by fnichol** [comment]
@portertech I bet `no_parallel_for` was added after your implementation. I needed this to make the Vagrant driver "concurrent" even though `up` and `destroy` actions are not concurrent safe. If you add `--log-level debug` on any of the action commands, you'll see the instances "synchronizing" on `#create` or `#destroy`, then "entering" the mutex block.

Each driver class will get its own Mutex that is class-wide. In other words **all** Vagrant-backed instances will share the same Mutex whenever the enter `#create` or `#destroy`, but the remaining instances not Vagrant backed will continue on their own. I didn't want to slow down the world for the "fast" drivers.

**Comment by portertech** [comment]
Ran into an issue https://gist.github.com/portertech/ea5f8b5a81f2b2e872ef

**Comment by bryanwb** [comment]
it depends on this fix https://github.com/opscode/test-kitchen/commit/edf3ad7217af4609f8fff4e24de7d486c8c1d567

**Comment by portertech** [comment]
Seems that the issue I am having is related to nested exceptions, https://github.com/opscode/test-kitchen/blob/1.0/lib/kitchen/errors.rb#L31

**Comment by portertech** [comment]
@fnichol My issue is: a run_command() error, librarian-chef bin only in bundle (not system), doesn't bubble up, end up only seeing a "can't convert nil into String" (which I can't seem to pinpoint).

**Comment by fnichol** [comment]
@portertech ok, it's time get friendlier errors going. i've been toying with [this pattern](https://github.com/carlhuda/bundler/blob/master/bin/bundle#L20) from Bundler

**Pull request merged**
